version: '3'
services:
  mqttingress:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MODULE_NAME: mqttingress
      EGRESS_URLS: https://hookb.in/7Zd6n0JXV0TWNgjjNa3P
      MQTT_BROKER: mqtt://test.mosquitto.org
      PROTOCOL: mqtt
      TOPIC: weeve/hackathon/air-quality-monitor
      PORT: 1883
      QOS: 1
